In [255]:
import numpy as np

# Numpy Excercises - Session 2

### Exercise 1

Reshape `array1` to 7x3 dimensions.

In [256]:
array1 = np.arange(0, 21)
array1 = array1.reshape(7,3)
array1
#test1(array1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

### Exercise 2

Reshape `array2` into a 3D array of 3x3x3 dimensions.

In [257]:
array2 = np.arange(0, 27).reshape(9, 3)
array2 = array2.reshape(3,3,3)
array2 
#test2()

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

### Exercise 3: Reshape vs Resize

reshape and resize both do the same thin. So, what's the difference?

Follow the instructions and find out.


In [258]:
# Run this cell without changing the code.
array3 = np.arange(0, 9)

array3.reshape(3, 3)
print(array3)

array3.resize((3, 3))
print(array3)


[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [259]:
# Question: What is the difference between reshape and resize

a = "resize returns a new copy of the array, while reshape changes the original array"
b = "reshape returns a new copy of the array, while resize changes the original array"
c = "both resize and reshape works in the same way with the original array"
b
#test3()

'reshape returns a new copy of the array, while resize changes the original array'

### Exercise 4

Concatenate arrays `a`, `b`, and `c`.

In [260]:
a = np.arange(0, 3)
b = np.arange(3, 6)
c = np.arange(6, 9)
array4 = np.concatenate((a,b,c))
array4 
#test4(array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### Exercise 5

Concatenate arrays `m1` and `m2` vertically.

In [261]:
m1 = np.array(
    [
      [1, 2, 3, 4],
      [5, 6, 7, 8]
    ]
)

m2 = np.array(
    [
      [9, 10, 11, 12],
      [13, 14, 15, 16]
    ]
)

array5 = np.concatenate((m1,m2))
array5
#test5(array5)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### Exercise 6

Concatenate arrays `m1` and `m2` horizontally.

In [262]:
m1 = np.array(
    [
      [1, 2, 3, 4],
      [5, 6, 7, 8]
    ]
)

m2 = np.array(
    [
      [9, 10, 11, 12],
      [13, 14, 15, 16]
    ]
)

array6 = np.concatenate((m1,m2), axis=1)
array6 
#test6(array7)

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

### Exercise 7

Get all the cells with value equals to `0` as a list of tuples.


In [263]:
matrix = np.array([
    [1, 4, 7, 5, 0],
    [0, 2, 9, 0, 1],
    [3, 6, 0, 5, 3],
    [7, 3, 0, 1, 0],
    [3, 6, 1, 0, 4],
])
coordinates = np.where(matrix==0)
array7 = list(zip(coordinates[0], coordinates[1]))
array7 
#test5(array7)

[(0, 4), (1, 0), (1, 3), (2, 2), (3, 2), (3, 4), (4, 3)]

### Exercise 8

Check the documentation for `np.diag` and `np.fliplr`. Use them to extract the diagonals arrays for `matrix`.



In [264]:
diag1 = np.diag(matrix)
print(diag1)
diag2 = np.diag(np.fliplr(matrix))
print(diag2)
#testDiag1(diag1)
#testDiag2(diag2)

[1 2 0 1 4]
[0 0 0 3 3]


### Exercise 9

Get the values of the 3th column in `matrix` and the values for the 2th row in `matrix`. Both as numpy arrays.


In [265]:

column = matrix[:,2]
print(column) 
row = matrix[1,:]
print(row)
#testColumn(column)
#testRow(row)

[7 9 0 0 1]
[0 2 9 0 1]


## Exercise 10

Create a new matrix ***x*** from ***a*** and ***m*** with the folowing structure:



```
array([[4, 4, 5, 4, 4],
       [4, 4, 5, 4, 4],
       [4, 4, 5, 4, 4]])
```



In [266]:
a = np.full((3, 1), 5)
m = np.full((3, 4), 4)

m_splitted = np.hsplit(m,2)
x = np.hstack((m_splitted[0],a,m_splitted[1]))
x 

array([[4, 4, 5, 4, 4],
       [4, 4, 5, 4, 4],
       [4, 4, 5, 4, 4]])

## Exercise 11

Given a:

```
a = array([[1],
       [1],
       [2],
       [4]])
```

Create a new array **b** with the following structure:

```
np.array([
  [1, 0, 0],
  [1, 0, 0],
  [0, 1, 0],
  [0, 0, 1],
])
```
Do you detect the pattern? Which operation do you need to create this structure.?




In [267]:
# one hot encode excersise for numpy 
# a = np.array([[1], [1], [2], [4]]).reshape(-1)
a = np.array([[1], [1], [2], [4]])
categories = np.array([1,2,4])
(np.bitwise_and(a, categories)>0).astype(int)



array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# Challenge, Tic Tac Toe


In [268]:
cell = {
    0: ' ',
    1: 'X',
    2: 'O'
}

def print_board():
  print('-------------')
  print(f'| {cell[game[0][0]]} | {cell[game[0][1]]} | {cell[game[0][2]]} |')
  print('-------------')
  print(f'| {cell[game[1][0]]} | {cell[game[1][1]]} | {cell[game[1][2]]} |')
  print('-------------')
  print(f'| {cell[game[2][0]]} | {cell[game[2][1]]} | {cell[game[2][2]]} |')
  print('-------------')

def skynet_move():
  # Select a random empty cell in `game` array and set with value `2`.
  # If no empty cells available, do nothing.
  empty_cells = np.where(game==0)
  empty_cells_coor = list(zip(empty_cells[0], empty_cells[1]))
  if (len(empty_cells_coor)>0):
    random_cell = empty_cells_coor[np.random.randint(len(empty_cells_coor))]
    game[random_cell[0],random_cell[1]] = 2


def win_move(player, r, c):
  # Check if the player's move is a win move.
  # A win move meets one of these conditions:
  #   - All values at row `r` are equal to `player`.
  #   - All values at column `c` are equal to `player`.
  #   - All values at main diagonal ((0, 0) to (2, 2)) are equal to  `player`.
  #   - All values at second diagonal ((2, 0) to (0, 2)) are equal to  `player`.
  # Return True if one of the conditions are met, False otherwise.
  if (np.all(game[r,:] == player) or np.all(game[:,c] == player) or np.all(np.diag(game) == player) or np.all(np.diag(np.fliplr(game)) == player)):
    global winner 
    winner = True    
    return True
  else:
    return False    


def human_move(r, c):
  # Set value `1` at game[r][c] if the cell if empty and return True.
  # If cell is not empty print "Cell is not empty" and return False.
  if (game[r][c] == 0):
    game[r][c] = 1
    return True
  else:
    print("Cell is not empty")
    return False

def winner_exists():
  # If one of the players has already won the game, return True.
  # Return False otherwise.  
  return winner


def is_game_on():
  # This method checks the current status of the game.
  # A game is on if meets one of two conditios:
  #  - There is still available cells.
  #  - There is still no winners.  
  if (game[game==0].ndim > 0 and not winner_exists()):
    return True
  else: 
    return False

In [269]:
# Run this cell to restart the game.

# Create a 3x3 array with zero values.
game = np.zeros((3,3))
winner = False

In [270]:
#@title Tic tac toe controls
#@markdown Select the cell for your next move!.
row_value = "2" #@param ["0", "1", "2"] 
column_value = "2" #@param ["0", "1", "2"]

row = int(row_value)
column = int(column_value)
if(is_game_on()):
  status = human_move(row, column)
  if(win_move(1, row, column)):    
    print('Human wins')
  elif(status):
    skynet_move()
    if(win_move(2, row, column)):
      print('Skynet wins')
else:
  print('Game over.') 
print_board()

-------------
|   |   |   |
-------------
|   |   |   |
-------------
| O |   | X |
-------------


# Challenge: Basic data analysis

The following numpy array is taken from the a census dataset. Every column in this matrix contains some demografic information. For this exercise You will focus in the following columns:

*   Column[0]: Age
*   Column[1]: workclass
*   Column[3]: education
*   Column[5]: marital-status
*   Column[9]: sex
*   Column[10]: capital-gain

Please find the following information:


*   Age average
*   Types of workclass, education and marital-status
*   How many records are for male
*   How many records are for female
*   How many females are above age of 30
*   Avergage of capital-gain for males
*   Avergage of capital-gain for females







In [271]:
# First upload file "census.npy" befor running this cell.
with open('census.npy', 'rb') as f:
  census_data = np.load(f, allow_pickle=True)
census_data

array([[50, ' Self-emp-not-inc', 83311, ..., 13, ' United-States',
        ' <=50K'],
       [38, ' Private', 215646, ..., 40, ' United-States', ' <=50K'],
       [53, ' Private', 234721, ..., 40, ' United-States', ' <=50K'],
       ...,
       [58, ' Private', 151910, ..., 40, ' United-States', ' <=50K'],
       [22, ' Private', 201490, ..., 20, ' United-States', ' <=50K'],
       [52, ' Self-emp-inc', 287927, ..., 40, ' United-States', ' >50K']],
      dtype=object)

In [272]:
male_records = census_data[np.char.strip(census_data[:,9].astype(str)) == 'Male']
female_records = census_data[np.char.strip(census_data[:,9].astype(str)) == 'Female']

In [273]:
avg_age = np.average(census_data[:,0].astype(int))
print(f'average age: {avg_age}')

average age: 38.581633906633904


In [274]:
workclass_types = np.unique(census_data[:,1])
print(f'worklass types: {workclass_types}')
education_types = np.unique(census_data[:,3])
print(f'education types: {education_types}')
marital_status_types = np.unique(census_data[:,5])
print(f'marital-status types: {marital_status_types}')

worklass types: [' ?' ' Federal-gov' ' Local-gov' ' Never-worked' ' Private'
 ' Self-emp-inc' ' Self-emp-not-inc' ' State-gov' ' Without-pay']
education types: [' 10th' ' 11th' ' 12th' ' 1st-4th' ' 5th-6th' ' 7th-8th' ' 9th'
 ' Assoc-acdm' ' Assoc-voc' ' Bachelors' ' Doctorate' ' HS-grad'
 ' Masters' ' Preschool' ' Prof-school' ' Some-college']
marital-status types: [' Divorced' ' Married-AF-spouse' ' Married-civ-spouse'
 ' Married-spouse-absent' ' Never-married' ' Separated' ' Widowed']


In [275]:
%time male_records_nummber = np.count_nonzero(male_records[:,0]) 
print(f'male records: {male_records_nummber}')
#alternative
%time male_records_nummber2 = male_records.shape[0]
print(f'male records: {male_records_nummber2}')



CPU times: user 548 µs, sys: 0 ns, total: 548 µs
Wall time: 558 µs
male records: 21789
CPU times: user 6 µs, sys: 0 ns, total: 6 µs
Wall time: 9.06 µs
male records: 21789


In [276]:
%time male_records_nummber = np.count_nonzero(female_records[:,0]) 
print(f'female records: {male_records_nummber}')
#alternative
%time male_records_nummber2 = female_records.shape[0]
print(f'female records: {male_records_nummber2}')

CPU times: user 262 µs, sys: 0 ns, total: 262 µs
Wall time: 296 µs
female records: 10771
CPU times: user 5 µs, sys: 0 ns, total: 5 µs
Wall time: 9.06 µs
female records: 10771


In [277]:
females_over_30 = female_records[female_records[:,0].astype(int) > 30].shape[0]
print(f'females over 30: {females_over_30}')

females over 30: 6512


In [278]:
avg_gain_males =  np.average(male_records[:,10].astype(int))
print(f'average male gains: {avg_gain_males}')

average male gains: 1329.3313139657625


In [279]:
avg_gain_females =  np.average(female_records[:,10].astype(int))
print(f'average female gains: {avg_gain_females}')

average female gains: 568.4105468387336
